version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - myapp-network

  backend:
    image: student-database-cosa
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - myapp-network

  frontend:
    image: my-react-app
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
